name: Python Application

on:
  push:
    branches: [ master  ]
  pull_request:
    branches: [ master  ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Copying Repo
      uses: actions/checkout@v3

    - name: Python Setting Up
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Loading Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Running Tests
      run: |
        pytest